server.address=0.0.0.0
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/ctdt_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=iambatman
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.com.ctdt=INFO
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG